from maspy import *
# autogenerated
# (c) cainan - utfpr 2024
class CoffeeMachine(Agent):
    def __init__(self, name):
        super().__init__(name)
        self.add(Belief('HasWater'))
        self.add(Belief('HasFilter'))

    @pl(gain, Belief("HasWater"), Belief("HasCoffeeBean"))
    def ExpressoReady(self):
        self.add(Goal("MakeCoffee"))
    @pl(gain, Belief("HasCoffeeBean"))
    def BuyFilter(self):
        self.add(Belief("HasFilter"))
    @pl(gain, Belief("HasWater"), Belief("HasFilter"))
    def BlackReady(self):
        self.add(Goal("MakeCoffee"))
    @pl(gain, Belief("HasWater"), Goal("MakeCoffee"))
    def MakeCoffee(self):
        pass
    
# autogenerated
# (c) cainan - utfpr 2024
class CoffeeShop(Environment):
    def __init__(self, name):
        super().__init__(name)
        self.create(Percept('hasCoffee'))

    def buyCoffee(self, src):
        pass

